using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Printing;

namespace FlyCn.FlyCnDAL
{
    public class ExcelReportSettings
    {
        #region Properties
        public string reportHeader
        {
            get;
            set;
        }
        public string reportLogo
        {
            get;
            set;
        }
        public string reportGeneratedBy
        {
            get;
            set;
        }
        public bool isGeneratedDateRequired
        {
            get;
            set;
        }
        public string orientation
        {
            get;
            set;
        }
        public string printSize
        {
            get;
            set;
        }
        public bool isClientLogoRequired
        {
            get;
            set;
        }
        public string pageTitle
        {
            get;
            set;
        }
        #endregion Properties

        #region GenerateReport
        public void GenerateReport(Microsoft.Office.Interop.Excel.Worksheet ws)
        {
            Microsoft.Office.Interop.Excel.Range chartRange = ws.get_Range("A1", "z2");
            UIClasses.Const Const = new UIClasses.Const();
            FlyCnDAL.Security.UserAuthendication UA;

            HttpContext context = HttpContext.Current;
            UA = (FlyCnDAL.Security.UserAuthendication)context.Session[Const.LoginSession];
            reportGeneratedBy = UA.userName;

            //--------------------------Cell font color , size--------------------------//
            Microsoft.Office.Interop.Excel.Range formatRange;
            formatRange = ws.get_Range("A1", "z2");
            formatRange.Font.Color = System.Drawing.ColorTranslator.ToOle(System.Drawing.Color.Black);
            formatRange.Font.Size = 15;

            //-------------------Cell background color----------------//
            Microsoft.Office.Interop.Excel.Range formatRange1;
            formatRange1 = ws.get_Range("A1", "z2");
            formatRange1.Interior.Color = System.Drawing.
            ColorTranslator.ToOle(System.Drawing.Color.Bisque);

            //----------------------Adding Custom header to the excel file--------------//
            ws.get_Range("a1", "b1").Merge(false);
            chartRange = ws.get_Range("a1", "b1");
            chartRange.FormulaR1C1 = "Flycn";
            chartRange.HorizontalAlignment = 3;
            chartRange.VerticalAlignment = 3;

            //-------------------footer background color----------------//
            Microsoft.Office.Interop.Excel.Range formatFooter;
            formatFooter = ws.get_Range("A30", "z31");
            formatFooter.Interior.Color = System.Drawing.
            ColorTranslator.ToOle(System.Drawing.Color.Bisque);


            //----------------------Generated By--------------//
            ws.get_Range("j30", "n30").Merge(false);
            chartRange = ws.get_Range("j30", "n30");
            chartRange.FormulaR1C1 = "Generated By : " + reportGeneratedBy;
            ws.get_Range("j30", "n30").Cells.Font.Size = 12;
            chartRange.HorizontalAlignment = 3;
            chartRange.VerticalAlignment = 3;

            //----------------------Page Title--------------//
            ws.get_Range("f2", "k2").Merge(false);
            chartRange = ws.get_Range("f2", "k2");
            chartRange.FormulaR1C1 = pageTitle;
            ws.get_Range("f2", "k2").Cells.Font.Size = 20;
            chartRange.HorizontalAlignment = 3;
            chartRange.VerticalAlignment = 3;


          
            //---------------insert logo---------------------------//
            object misValue = System.Reflection.Missing.Value;

            ws.Shapes.AddPicture("E:\\Applications\\FlyCn1.1_New\\FlyCn\\Images\\flycnLogo.png", Microsoft.Office.Core.MsoTriState.msoFalse, Microsoft.Office.Core.MsoTriState.msoCTrue, 70, 3, 25, 25);

            //set print paper size as A4    
            ws.PageSetup.PaperSize = Microsoft.Office.Interop.Excel.XlPaperSize.xlPaperA4;

            if (isGeneratedDateRequired == true)
            {

                ws.get_Range("a31", "z31").Merge(false);
                chartRange = ws.get_Range("j31", "n31");
                chartRange.FormulaR1C1 = "Generated Date : " + DateTime.Now.ToString("dd-MM-yyyy");
                ws.get_Range("j31", "n31").Cells.Font.Size = 12;
                chartRange.HorizontalAlignment = 3;
                chartRange.VerticalAlignment = 3;
            }

            if (orientation == "Portrait")
            {
                ws.PageSetup.Orientation = Microsoft.Office.Interop.Excel.XlPageOrientation.xlPortrait;
            }
            else
            {
                ws.PageSetup.Orientation = Microsoft.Office.Interop.Excel.XlPageOrientation.xlLandscape;
            }

            if (isClientLogoRequired == true)
            {

            }
           
            ws.HPageBreaks.Add(ws.Range["A33"]);
            ws.VPageBreaks.Add(ws.Range["o1"]);
            ws.HPageBreaks.Add(ws.Range["A64"]);
            ws.VPageBreaks.Add(ws.Range["o34"]);
            ws.PageSetup.CenterHeader = pageTitle;
        }
        #endregion GenerateReport 
    }
}